---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hc-clone
  namespace: hackerrank-clone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hackerrank-clone
  name: pod-creator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: hackerrank-clone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: hc-clone
  namespace: hackerrank-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-frontend
  namespace: hackerrank-clone
spec:
  selector:
    matchLabels:
      app: hc-frontend
  template:
    metadata:
      labels:
        app: hc-frontend
    spec:
      containers:
      - name: hc-frontend
        image: patnaikshekhar/hr-clone-frontend
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: postgres-hc-postgresql
                key: postgresql-password
        - name: POSTGRES_HOST
          value: postgres-hc-postgresql
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      serviceAccount: hc-clone
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hc-frontend
#   namespace: hackerrank-clone
# spec:
#   type: LoadBalancer
#   selector:
#     app: hc-frontend
#   ports:
#   - port: 80
#     targetPort: 80