apiVersion: v1
kind: Pod
metadata:
  name: sample-submission
spec:
  containers:
  - name: submission
    image: patnaikshekhar/hr-clone-worker
    env:
    - name: SUBMISSION_ID
      value: "1"
    - name: POSTGRES_PASSWORD
      valueFrom:
          secretKeyRef:
            name: postgres-hc-postgresql
            key: postgresql-password
    - name: POSTGRES_HOST
      value: postgres-hc-postgresql
  restartPolicy: Never